## test_04_n_replace_non_persisted_task
## Description:
## Test that non-persisted tasks cannot be replaced on the same node

## Prerequisite:
## Create a plug-in that generates tasks and a replacement task
## to be replaced in the same plan

## Actions:
## 1. Create model items so plug-in will generate a task:
##    task1(foo1, bar1)
## 2. Create plan
## 3. Run plan
## 4. Update the model item so the plug-in will generates tasks
##    and a replacement task
##    plug-in task2:(foo2, bar2)
##    plug-in task3: (foo3, bar3), replaces: (foo1, bar1) and (foo2, bar2)
## 5. Create plan
## 6. Check Error raised

## Results:
## Core will log an error and fail the create_plan when
## the Config Task to be replaced is present in the same plan

#Prerequisite:
#Create a plug-in that generates tasks and a replacement task
#to be replaced in the same plan
add-plugins plugins/story10650_plugin
add-extensions extensions/story10650_extension

runLitpScript ../include/two_nodes.at

#1. Create model items so plug-in will generate a task:
#   task1(foo1, bar1)
litp create -p /software/items/item1 -t story10650 -o name="tc04_foobar1"
litp inherit -s /software/items/item1 -p /deployments/local/clusters/cluster1/nodes/node1/items/item1

#2. Create plan
litp create_plan

#3. Run plan
litp run_plan

#4.Update the model item so the plug-in will generates tasks
#    and a replacement task
#   plug-in task2:(foo2, bar2)
#   plug-in task3: (foo3, bar3), replaces: (foo1, bar1) and (foo2, bar2)
litp update -p /software/items/item1 -o name="tc04_foobar2"

#5. Create plan
#6. Check Error raised
assertError create_plan --err_type "InternalServerError" --err_message "Task validation errors occurred"
assertLogMessage 'ERROR - A task is trying to replace another task ("foo2", "bar2") for node "node1" defined in current plan'
